FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive \
	&& ln -fs /usr/share/zoneinfo/UTC /etc/localtime

RUN apt-get update && apt-get install -y tzdata build-essential cmake git software-properties-common
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get install -y liblua5.1-dev libphysfs-dev zlib1g-dev libssl-dev libglew-dev \
	libopenal-dev libvorbis-dev libboost-all-dev libasio-dev liblzma-dev nlohmann-json3-dev

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt-get install -y g++-11
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20 && \
	update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 20 && \
	update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 20

WORKDIR /
RUN git clone https://github.com/icculus/physfs.git
WORKDIR /physfs
RUN git checkout stable-3.0 && mkdir build
WORKDIR /physfs/build
RUN cmake .. && make && make install && mv /usr/local/lib/libphysfs.a /usr/lib/x86_64-linux-gnu/.
WORKDIR /
RUN rm -fr /physfs

RUN apt-get autoremove -y git && apt-get clean && apt-get autoclean

VOLUME /otclient
WORKDIR /otclient

CMD ["./compile.sh"]
